"""initial schema

Revision ID: 62bcffeae5f9
Revises: 
Create Date: 2026-05-20 12:40:08.518943

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '62bcffeae5f9'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('task_history', schema=None) as batch_op:
        batch_op.add_column(sa.Column('progress_percent', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('progress_message', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('error_traceback', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('duration_ms', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('task_history', schema=None) as batch_op:
        batch_op.drop_column('duration_ms')
        batch_op.drop_column('error_traceback')
        batch_op.drop_column('progress_message')
        batch_op.drop_column('progress_percent')

    # ### end Alembic commands ###
