"""add schedules table

Revision ID: 90a1572bf135
Revises: 62bcffeae5f9
Create Date: 2026-05-20 12:51:10.178844

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '90a1572bf135'
down_revision: Union[str, None] = '62bcffeae5f9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('schedules',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('plugin_name', sa.String(), nullable=False),
    sa.Column('feature_id', sa.String(), nullable=True),
    sa.Column('cron_expr', sa.String(), nullable=False),
    sa.Column('params_json', sa.Text(), nullable=True),
    sa.Column('enabled', sa.Boolean(), nullable=True),
    sa.Column('last_run_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('schedules', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_schedules_plugin_name'), ['plugin_name'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('schedules', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_schedules_plugin_name'))

    op.drop_table('schedules')
    # ### end Alembic commands ###
